# Generated by Django 6.0 on 2025-12-06 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('certificate', 'Professional Certificate'), ('license', 'Business License'), ('portfolio', 'Portfolio'), ('reference', 'Reference Letter'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='artisan_documents/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('year_completed', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('masonry', 'Masonry'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('welding', 'Welding'), ('roofing', 'Roofing'), ('tiling', 'Tiling'), ('landscaping', 'Landscaping'), ('interior_design', 'Interior Design'), ('plastering', 'Plastering'), ('metalwork', 'Metalwork'), ('glass_work', 'Glass Work'), ('flooring', 'Flooring'), ('fencing', 'Fencing'), ('other', 'Other')], max_length=50)),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('certifications', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID for verification', max_length=20)),
                ('id_verified', models.BooleanField(default=False)),
                ('total_completed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_time_hours', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_artisans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_verified', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=100)),
                ('reference_phone', models.CharField(max_length=20)),
                ('reference_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(help_text='e.g., Former Client, Employer', max_length=100)),
                ('project_description', models.TextField(blank=True)),
                ('contact_permission', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('verification_turnaround', 'Verification Turnaround Time'), ('dispute_resolution', 'Dispute Resolution Rate'), ('platform_trust', 'Platform Trust Score'), ('user_retention', 'User Retention Rate'), ('transaction_volume', 'Transaction Volume'), ('active_users', 'Active Users'), ('new_signups', 'New Signups'), ('project_completion', 'Project Completion Rate'), ('fraud_prevention', 'Fraud Prevention Rate'), ('user_satisfaction', 'User Satisfaction Score')], max_length=50)),
                ('value', models.FloatField()),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='users_platf_metric__9e533f_idx')],
                'unique_together': {('metric_type', 'period', 'recorded_at')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('homeowner', 'Homeowner'), ('artisan', 'Artisan'), ('admin', 'Administrator')], default='homeowner', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_verification', 'User Verification'), ('document_approval', 'Document Approval'), ('dispute_resolution', 'Dispute Resolution'), ('user_suspension', 'User Suspension'), ('content_moderation', 'Content Moderation'), ('payment_release', 'Payment Release'), ('platform_update', 'Platform Update'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='users_admin_admin_i_1f956c_idx'), models.Index(fields=['action_type', 'created_at'], name='users_admin_action__5b8975_idx')],
            },
        ),
    ]
